Terrae_MapScripts::
	.byte 0

Terrae_EventScript_Resident01::
	msgbox Terrae_Text_Resident01, MSGBOX_NPC
	end

Terrae_Text_Resident01:
	.string "Terrae pode ser pequena, \n"
	.string "mas e um otimo lugar para viver!$"

Terrae_Playerhouse_1F_EventScripts::
	msgbox Terrae_Text_Mom01, MSGBOX_NPC
	end

Terrae_Text_Mom01:
	.string "Você esta se alimentando direito?$"

Terrae_ProfStar_EventScripts::
	msgbox Terrae_Text_ProfStar01, MSGBOX_NPC
	end

Terrae_Text_ProfStar01:
	.string "O cosmo se alinhou certinho,\n"
	.string "Hoje sera um dia especial!$"

Terrae_Lina_EventScript::
	msgbox Terrae_Text_Lina01, MSGBOX_NPC
	end

Terrae_Text_Lina01:
	.string "Entao, voce ta afim de uma batalha?$"

Terrae_Charlie_EventScripts::
	msgbox Terrae_Text_Charlie01, MSGBOX_NPC
	end

Terrae_Text_Charlie01:
	.string "Me vencer? so nascendo denovo!$"

Terrae_Resident02_EventScript::
	msgbox Terrae_Text_MaleCouple01, MSGBOX_NPC
	end

Terrae_Text_MaleCouple01:
	.string "Estamos nos mudando para Terrae, \n"
	.string "Um lugar calmo para criar nossa familia !$"

Terrae_Resident03_EventScript::
	msgbox Terrae_Text_FemCouple01, MSGBOX_NPC
	end

Terrae_Text_FemCouple01:
	.string "Meu marido comprou essa casaa aqui em Terrae, \n"
	.string "Nosso sonho finalmente se realizando !$"
